In [1]:
# loading the dataset

In [2]:
#loading the libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#loading the dataset

In [5]:
a=pd.read_json("/content/sample_data/Subscription_Boxes.jsonl.gz", lines=True, compression='gzip')
a

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,1,USELESS,Absolutely useless nonsense and a complete was...,[],B07G584SHG,B09WC47S3V,AEMJ2EG5ODOCYUTI54NBXZHDJGSQ,2020-10-08 05:10:57.705,2,True
1,2,Manufactured where?,"With a couple of the items, I wasn't quite sur...",[],B07QL1JRCN,B07QL1JRCN,AEEJBFZKUBEEMBZUZJV4UHFVEEBQ,2020-12-27 23:12:15.433,20,True
2,1,Little bang for your buck.,Two SMALL stuffed animals and 2 little bags of...,[],B07RBYJN37,B08N5QKX1Y,AGSVZNZBTSGQBKZDZTQYEZHGDPCQ,2021-01-06 12:48:35.319,4,True
3,5,New favorite box,"Although I don’t remember signing up for this,...",[],B07KM6T8GV,B07KM6T8GV,AFDERNB6BIR3U2DOR3S2KX7KJJXQ,2021-03-19 12:19:11.887,1,True
4,5,Coctique,I loved every thing and could use it all. Thin...,[],B07NVL6TJG,B07NVKNVNM,AE6P2YJ6FKX332MD56GPJFSHXNJQ,2019-06-03 03:40:06.066,0,True
...,...,...,...,...,...,...,...,...,...,...
16211,5,Very pleased,My husband loved it and look forward to seeing...,[],B08DDJ1QRS,B09TMNNYWH,AGX4UTCIP4SGTHHDA4E3WGPIJFBQ,2020-12-24 21:50:27.043,0,True
16212,1,??????,Y’all can do so much better. One pop one mini?...,[],B07GNX34XV,B07GNX34XV,AH4WBYSLGIAMVLCT2PPRTMNNJD6A,2019-03-16 19:32:07.421,1,True
16213,5,Always a great surprise inside,I’ve been a member for a few years now and I’v...,[{'small_image_url': 'https://images-na.ssl-im...,B07VXY755K,B07VXY755K,AHUTNTBX5E65YNIHI2ERA2AMFM4Q,2019-12-05 21:09:56.049,13,False
16214,1,"If you’re looking for a box, you have the wron...",First few boxes were great. Higher value items...,[{'small_image_url': 'https://m.media-amazon.c...,B07VXY755K,B07VXY755K,AF6RXEUYBSSOMO5RSS23OPB5QKSA,2022-06-29 13:42:43.413,6,True
16215,1,Cheap plastic gadgets you would never buy.,Each product in the box is cheap plastic gadge...,[],B07VXY755K,B07VXY755K,AHNDJGN3XW2IH2HQFTNSNOKB6NSQ,2021-07-17 21:38:24.080,8,False

In [6]:
a.columns

Index(['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id',
       'timestamp', 'helpful_vote', 'verified_purchase'],
      dtype='object')

In [7]:
b=pd.read_json("/content/sample_data/meta_Subscription_Boxes.jsonl.gz", lines=True, compression='gzip')
b

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,SUBSCRIPTION BOXES,Loved Again Media - Movie Subscription Box - 1...,4.1,75,[10 gently used DVDs delivered to your door ev...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Loved Again Media,[],{},B08W5BSH6V,NaN
1,SUBSCRIPTION BOXES,Bravado Music Icons T-Shirt Club Subscription ...,3.9,329,[WHAT IS T-SHIRT CLUB? Created for the ultimat...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Bravado Music Icons,[],{},B08MV3QHL8,NaN
2,SUBSCRIPTION BOXES,Succulents Box - 2 Succulents 2 Clay Pots Subs...,3.8,928,[You'll receive a box of succulents in clay po...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],SUCCULENTS BOX,[],{},B084KPB9K8,NaN
3,SUBSCRIPTION BOXES,The Legend of Vox Machina T-Shirt Club Subscri...,4.4,47,[WHAT IS T-SHIRT CLUB? Created for the ultimat...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],The Legend of Vox Machina,[],{},B09YYGB4BH,NaN
4,SUBSCRIPTION BOXES,50 States Of Mine - Premium Subscription Box: ...,4.6,6,[6-10 quality curated items from a different s...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],50 States Of Mine,[],{},B092MLYDGR,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,SUBSCRIPTION BOXES,IScape & Relax subscription box,5.0,4,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],IScape Candle Co.,[],{},B0B3F1NJLQ,NaN
637,SUBSCRIPTION BOXES,Funko Marvel Collector Corps: Ant-Man and The ...,4.4,55,[The Marvel Collector Corps subscription box c...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Funko,[],{},B0BM567CT3,NaN
638,SUBSCRIPTION BOXES,World’s Finest Collection Box –The Officially ...,4.1,144,[The World’s Finest Collection Box is a unique...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],DC Comics,[],{},B07MJBNCBW,NaN
639,SUBSCRIPTION BOXES,Funko Marvel Collector Corp Subscription Box: ...,4.6,113,[The Marvel Collector Corps subscription box c...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Funko,[],{},B0BM23TXKZ,NaN
640,SUBSCRIPTION BOXES,Naruto Shippuden T-Shirt Club Subscription – M...,4.0,8,[WHAT IS T-SHIRT CLUB? Created for the ultimat...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Naruto Shippuden,[],{},B0B94PL795,NaN

In [8]:
b.columns

Index(['main_category', 'title', 'average_rating', 'rating_number', 'features',
       'description', 'price', 'images', 'videos', 'store', 'categories',
       'details', 'parent_asin', 'bought_together'],
      dtype='object')

In [9]:
# merge both datasets

In [10]:
merged_df = pd.merge(a, b, on='parent_asin', how='left')

# Rename ambiguous columns for clarity
merged_df.rename(columns={
    'title_x': 'review_title',
    'title_y': 'product_title',
    'images_x': 'review_images',
    'images_y': 'product_images'
}, inplace=True)

In [11]:
merged_df

,rating,review_title,text,review_images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,...,rating_number,features,description,price,product_images,videos,store,categories,details,bought_together
0,1,USELESS,Absolutely useless nonsense and a complete was...,[],B07G584SHG,B09WC47S3V,AEMJ2EG5ODOCYUTI54NBXZHDJGSQ,2020-10-08 05:10:57.705,2,True,...,2962,[The best-selling cat subscription box! Get a ...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],KitNipBox,[],{},NaN
1,2,Manufactured where?,"With a couple of the items, I wasn't quite sur...",[],B07QL1JRCN,B07QL1JRCN,AEEJBFZKUBEEMBZUZJV4UHFVEEBQ,2020-12-27 23:12:15.433,20,True,...,1207,[No Samples! 4-5 Full-Size Lip Products Every ...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Lip Monthly,[],{},NaN
2,1,Little bang for your buck.,Two SMALL stuffed animals and 2 little bags of...,[],B07RBYJN37,B08N5QKX1Y,AGSVZNZBTSGQBKZDZTQYEZHGDPCQ,2021-01-06 12:48:35.319,4,True,...,3385,[What is BarkBox? A monthly dog box delivery o...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Barkbox,[],{},NaN
3,5,New favorite box,"Although I don’t remember signing up for this,...",[],B07KM6T8GV,B07KM6T8GV,AFDERNB6BIR3U2DOR3S2KX7KJJXQ,2021-03-19 12:19:11.887,1,True,...,463,[NEW REDHEAD BEAUTY PRODUCTS EVERY MONTH: Trea...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],How to Be A Redhead,[],{},NaN
4,5,Coctique,I loved every thing and could use it all. Thin...,[],B07NVL6TJG,B07NVKNVNM,AE6P2YJ6FKX332MD56GPJFSHXNJQ,2019-06-03 03:40:06.066,0,True,...,1661,"[AS SEEN IN: Oprah Daily, InStyle, Byrdie, My ...",[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],COCOTIQUE,[],{},NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16211,5,Very pleased,My husband loved it and look forward to seeing...,[],B08DDJ1QRS,B09TMNNYWH,AGX4UTCIP4SGTHHDA4E3WGPIJFBQ,2020-12-24 21:50:27.043,0,True,...,945,[WHAT IS T-SHIRT CLUB? Created for the ultimat...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Star Trek,[],{},NaN
16212,1,??????,Y’all can do so much better. One pop one mini?...,[],B07GNX34XV,B07GNX34XV,AH4WBYSLGIAMVLCT2PPRTMNNJD6A,2019-03-16 19:32:07.421,1,True,...,1613,[The Star Wars Smuggler’s Bounty subscription ...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Funko,[],{},NaN
16213,5,Always a great surprise inside,I’ve been a member for a few years now and I’v...,[{'small_image_url': 'https://images-na.ssl-im...,B07VXY755K,B07VXY755K,AHUTNTBX5E65YNIHI2ERA2AMFM4Q,2019-12-05 21:09:56.049,13,False,...,82,[BREO BOX: A curated quarterly box full of the...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{},NaN
16214,1,"If you’re looking for a box, you have the wron...",First few boxes were great. Higher value items...,[{'small_image_url': 'https://m.media-amazon.c...,B07VXY755K,B07VXY755K,AF6RXEUYBSSOMO5RSS23OPB5QKSA,2022-06-29 13:42:43.413,6,True,...,82,[BREO BOX: A curated quarterly box full of the...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{},NaN
16215,1,Cheap plastic gadgets you would never buy.,Each product in the box is cheap plastic gadge...,[],B07VXY755K,B07VXY755K,AHNDJGN3XW2IH2HQFTNSNOKB6NSQ,2021-07-17 21:38:24.080,8,False,...,82,[BREO BOX: A curated quarterly box full of the...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{},NaN

In [12]:
# to check if there are any missing data

In [13]:
merged_df.isnull().sum()

rating                   0
review_title             0
text                     0
review_images            0
asin                     0
parent_asin              0
user_id                  0
timestamp                0
helpful_vote             0
verified_purchase        0
main_category            0
product_title            0
average_rating           0
rating_number            0
features                 0
description              0
price                16216
product_images           0
videos                   0
store                   15
categories               0
details                  0
bought_together      16216
dtype: int64

In [14]:
merged_df.drop(columns=['price', 'bought_together'], inplace=True)

In [15]:
merged_df

,rating,review_title,text,review_images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,...,product_title,average_rating,rating_number,features,description,product_images,videos,store,categories,details
0,1,USELESS,Absolutely useless nonsense and a complete was...,[],B07G584SHG,B09WC47S3V,AEMJ2EG5ODOCYUTI54NBXZHDJGSQ,2020-10-08 05:10:57.705,2,True,...,KitNipBox | Happy Cat Box | Monthly Cat Subscr...,4.1,2962,[The best-selling cat subscription box! Get a ...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],KitNipBox,[],{}
1,2,Manufactured where?,"With a couple of the items, I wasn't quite sur...",[],B07QL1JRCN,B07QL1JRCN,AEEJBFZKUBEEMBZUZJV4UHFVEEBQ,2020-12-27 23:12:15.433,20,True,...,Lip Monthly - Beauty and Makeup Subscription Box,3.1,1207,[No Samples! 4-5 Full-Size Lip Products Every ...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Lip Monthly,[],{}
2,1,Little bang for your buck.,Two SMALL stuffed animals and 2 little bags of...,[],B07RBYJN37,B08N5QKX1Y,AGSVZNZBTSGQBKZDZTQYEZHGDPCQ,2021-01-06 12:48:35.319,4,True,...,"BarkBox Monthly Subscription Box, Dog Chew Toy...",4.2,3385,[What is BarkBox? A monthly dog box delivery o...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Barkbox,[],{}
3,5,New favorite box,"Although I don’t remember signing up for this,...",[],B07KM6T8GV,B07KM6T8GV,AFDERNB6BIR3U2DOR3S2KX7KJJXQ,2021-03-19 12:19:11.887,1,True,...,How to be a Redhead - Redhead Friendly Approve...,3.8,463,[NEW REDHEAD BEAUTY PRODUCTS EVERY MONTH: Trea...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],How to Be A Redhead,[],{}
4,5,Coctique,I loved every thing and could use it all. Thin...,[],B07NVL6TJG,B07NVKNVNM,AE6P2YJ6FKX332MD56GPJFSHXNJQ,2019-06-03 03:40:06.066,0,True,...,COCOTIQUE - Beauty & Self-Care Subscription Bo...,4.2,1661,"[AS SEEN IN: Oprah Daily, InStyle, Byrdie, My ...",[],[{'thumb': 'https://m.media-amazon.com/images/...,[],COCOTIQUE,[],{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16211,5,Very pleased,My husband loved it and look forward to seeing...,[],B08DDJ1QRS,B09TMNNYWH,AGX4UTCIP4SGTHHDA4E3WGPIJFBQ,2020-12-24 21:50:27.043,0,True,...,Star Trek T-Shirt Club Subscription - Women - XL,4.1,945,[WHAT IS T-SHIRT CLUB? Created for the ultimat...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Star Trek,[],{}
16212,1,??????,Y’all can do so much better. One pop one mini?...,[],B07GNX34XV,B07GNX34XV,AH4WBYSLGIAMVLCT2PPRTMNNJD6A,2019-03-16 19:32:07.421,1,True,...,Funko Star Wars Smuggler's Bounty Box,4.5,1613,[The Star Wars Smuggler’s Bounty subscription ...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Funko,[],{}
16213,5,Always a great surprise inside,I’ve been a member for a few years now and I’v...,[{'small_image_url': 'https://images-na.ssl-im...,B07VXY755K,B07VXY755K,AHUTNTBX5E65YNIHI2ERA2AMFM4Q,2019-12-05 21:09:56.049,13,False,...,BREO BOX Lifestyle Subscription Box,3.4,82,[BREO BOX: A curated quarterly box full of the...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{}
16214,1,"If you’re looking for a box, you have the wron...",First few boxes were great. Higher value items...,[{'small_image_url': 'https://m.media-amazon.c...,B07VXY755K,B07VXY755K,AF6RXEUYBSSOMO5RSS23OPB5QKSA,2022-06-29 13:42:43.413,6,True,...,BREO BOX Lifestyle Subscription Box,3.4,82,[BREO BOX: A curated quarterly box full of the...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{}
16215,1,Cheap plastic gadgets you would never buy.,Each product in the box is cheap plastic gadge...,[],B07VXY755K,B07VXY755K,AHNDJGN3XW2IH2HQFTNSNOKB6NSQ,2021-07-17 21:38:24.080,8,False,...,BREO BOX Lifestyle Subscription Box,3.4,82,[BREO BOX: A curated quarterly box full of the...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{}

In [16]:
# filter the reviews..keeping the important ones

In [17]:
merged_df = merged_df[merged_df['helpful_vote'] > 2]

In [18]:
merged_df

,rating,review_title,text,review_images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,...,product_title,average_rating,rating_number,features,description,product_images,videos,store,categories,details
1,2,Manufactured where?,"With a couple of the items, I wasn't quite sur...",[],B07QL1JRCN,B07QL1JRCN,AEEJBFZKUBEEMBZUZJV4UHFVEEBQ,2020-12-27 23:12:15.433,20,True,...,Lip Monthly - Beauty and Makeup Subscription Box,3.1,1207,[No Samples! 4-5 Full-Size Lip Products Every ...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Lip Monthly,[],{}
2,1,Little bang for your buck.,Two SMALL stuffed animals and 2 little bags of...,[],B07RBYJN37,B08N5QKX1Y,AGSVZNZBTSGQBKZDZTQYEZHGDPCQ,2021-01-06 12:48:35.319,4,True,...,"BarkBox Monthly Subscription Box, Dog Chew Toy...",4.2,3385,[What is BarkBox? A monthly dog box delivery o...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Barkbox,[],{}
8,5,Big Boy Hearts Bark Box,There is no other subscription box for dogs li...,[{'small_image_url': 'https://images-na.ssl-im...,B07R7WVRGL,B08N5QKX1Y,AEDTXOC3YW6O7P2UPM22VNNRF77A,2019-07-15 22:37:43.551,3,False,...,"BarkBox Monthly Subscription Box, Dog Chew Toy...",4.2,3385,[What is BarkBox? A monthly dog box delivery o...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Barkbox,[],{}
13,5,Great selection!,I was pleasantly surprised by the selection in...,[],B07S5S45K7,B07S38196L,AE4ZYPZMKVBHBVXNRCD7R5JNIKCQ,2021-01-16 21:35:15.280,3,True,...,Bunny James Boxes - Keto Snack Subscription: 7...,3.6,99,"[Discover Premium Keto Snacks Every Month, 7 s...",[],[{'thumb': 'https://m.media-amazon.com/images/...,[],BUNNY · JAMES .,[],{}
16,4,A great Father's day gift,My husband is an excellent father so one fathe...,[],B08MV51CXP,B08MV3QHL8,AHJYOD56GVUHGUW6NV4US7JR6NDA,2021-06-23 06:43:05.090,7,True,...,Bravado Music Icons T-Shirt Club Subscription ...,3.9,329,[WHAT IS T-SHIRT CLUB? Created for the ultimat...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Bravado Music Icons,[],{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16205,5,Best Subscription Box!,This subscription box is one of my longest sta...,[],B07QC7BQ12,B07QC7KJNY,AEBJLDAL4PETHWA3Q2XSIKIDFPFQ,2019-06-08 16:21:04.951,6,False,...,Skivvie NIX Box - Underwear Subscription Box: ...,3.9,108,"[2 Thongs delivered monthly, A convenient upda...",[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Skivvie NIX,[],{}
16206,5,The perfect gift!!,Bought as a gift for my GF. She loves them. A ...,[],B07QHFMRL1,B07QC7KJNY,AFQ4CFKL53ZYUY56TO2HFKEZ4BNA,2019-04-29 21:45:25.250,4,False,...,Skivvie NIX Box - Underwear Subscription Box: ...,3.9,108,"[2 Thongs delivered monthly, A convenient upda...",[],[{'thumb': 'https://m.media-amazon.com/images/...,[],Skivvie NIX,[],{}
16213,5,Always a great surprise inside,I’ve been a member for a few years now and I’v...,[{'small_image_url': 'https://images-na.ssl-im...,B07VXY755K,B07VXY755K,AHUTNTBX5E65YNIHI2ERA2AMFM4Q,2019-12-05 21:09:56.049,13,False,...,BREO BOX Lifestyle Subscription Box,3.4,82,[BREO BOX: A curated quarterly box full of the...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{}
16214,1,"If you’re looking for a box, you have the wron...",First few boxes were great. Higher value items...,[{'small_image_url': 'https://m.media-amazon.c...,B07VXY755K,B07VXY755K,AF6RXEUYBSSOMO5RSS23OPB5QKSA,2022-06-29 13:42:43.413,6,True,...,BREO BOX Lifestyle Subscription Box,3.4,82,[BREO BOX: A curated quarterly box full of the...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{}
16215,1,Cheap plastic gadgets you would never buy.,Each product in the box is cheap plastic gadge...,[],B07VXY755K,B07VXY755K,AHNDJGN3XW2IH2HQFTNSNOKB6NSQ,2021-07-17 21:38:24.080,8,False,...,BREO BOX Lifestyle Subscription Box,3.4,82,[BREO BOX: A curated quarterly box full of the...,[],[{'thumb': 'https://m.media-amazon.com/images/...,[],breobox,[],{}

In [19]:
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [20]:
# CELL 11: Merge and filter (same as main notebook)
merged_df = pd.merge(a, b, on='parent_asin', how='left')
merged_df.rename(columns={
    'title_x': 'review_title', 'title_y': 'product_title',
    'images_x': 'review_images', 'images_y': 'product_images'
}, inplace=True)
merged_df.drop(columns=['price', 'bought_together'], inplace=True)
merged_df = merged_df[merged_df['helpful_vote'] > 2]
print(f"Filtered dataset: {merged_df.shape}")

Filtered dataset: (7340, 21)

In [21]:
# CELL 12 FINAL: TF-IDF Extractive Summarisation
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize
import numpy as np
import re

def clean_text(text):
    text = re.sub(r'<.*?>', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

feature_keywords = {
    "Product Quality"          : ["quality", "product", "item", "material", "cheap", "broke", "durable"],
    "Value for Money"          : ["price", "value", "worth", "expensive", "cost", "money", "overpriced"],
    "Packaging & Presentation" : ["packaging", "package", "box", "wrapped", "presentation", "damaged", "sealed"],
    "Delivery & Shipping"      : ["delivery", "shipping", "shipped", "arrived", "late", "fast", "delay"],
    "Variety & Curation"       : ["variety", "selection", "curated", "choice", "different", "unique", "range"],
    "Customer Service"         : ["service", "support", "refund", "response", "helpful", "rude", "resolved"]
}

def tfidf_summarise_sentences(reviews, top_n=2):
    all_sentences = []
    for review in reviews:
        review = clean_text(review)
        try:
            sents = sent_tokenize(review)
            sents = [s.strip() for s in sents
                     if 10 <= len(s.split()) <= 50]  # max 50 words
            all_sentences.extend(sents)
        except:
            continue

    if not all_sentences:
        return "No summary available."

    vectorizer = TfidfVectorizer(stop_words='english', max_features=500)
    try:
        tfidf_matrix = vectorizer.fit_transform(all_sentences)
    except:
        return all_sentences[0]

    scores = np.array(tfidf_matrix.sum(axis=1)).flatten()
    top_indices = np.argsort(scores)[::-1]

    seen, selected = set(), []
    for idx in top_indices:
        sent = all_sentences[idx]
        if sent not in seen:
            seen.add(sent)
            selected.append((idx, sent))
        if len(selected) == top_n:
            break

    selected.sort(key=lambda x: x[0])
    return " ".join([s for _, s in selected])

def tfidf_feature_summarise_sentences(reviews, keywords, top_n=1):
    all_sentences = []
    for review in reviews:
        review = clean_text(review)
        try:
            sents = sent_tokenize(review)
            sents = [s.strip() for s in sents
                     if 10 <= len(s.split()) <= 50]  # max 50 words
            all_sentences.extend(sents)
        except:
            continue

    relevant = [s for s in all_sentences
                if any(kw in s.lower() for kw in keywords)]

    if not relevant:
        relevant = all_sentences

    if len(relevant) < 2:
        return relevant[0] if relevant else "No summary available."

    vectorizer = TfidfVectorizer(stop_words='english', max_features=300)
    try:
        tfidf_matrix = vectorizer.fit_transform(relevant)
        scores = np.array(tfidf_matrix.sum(axis=1)).flatten()
        top_indices = np.argsort(scores)[::-1]
        seen, selected = set(), []
        for idx in top_indices:
            sent = relevant[idx]
            if sent not in seen:
                seen.add(sent)
                selected.append(sent)
            if len(selected) == top_n:
                break
        return " ".join(selected)
    except:
        return relevant[0]

# Run
all_reviews = merged_df['text'].dropna().tolist()
print(f"Total reviews: {len(all_reviews)}")

print("Generating TF-IDF Overall Summary...")
tfidf_overall = tfidf_summarise_sentences(all_reviews, top_n=2)

print("Generating TF-IDF Feature Summaries...")
tfidf_feature_summaries = {}
for feature, keywords in feature_keywords.items():
    tfidf_feature_summaries[feature] = tfidf_feature_summarise_sentences(
        all_reviews, keywords, top_n=1)
    print(f"  ✅ {feature}")

# Build summary dict
tfidf_summary_clean = {
    "Overall Summary": {
        "Summary"   : tfidf_overall,
        "Key Themes": "Quality, Value for Money, Customer Service, Variety"
    },
    "Feature-Based Summary": {
        feat: {"Summary": summ}
        for feat, summ in tfidf_feature_summaries.items()
    }
}

# Print
print("\n" + "="*65)
print("     TF-IDF EXTRACTIVE SUMMARY (FINAL)")
print("="*65)
print(f"\n📌 Overall Summary:\n{tfidf_overall}\n")
for feat, summ in tfidf_feature_summaries.items():
    print(f"📌 {feat}:\n{summ}\n")

Total reviews: 7340
Generating TF-IDF Overall Summary...
Generating TF-IDF Feature Summaries...
  ✅ Product Quality
  ✅ Value for Money
  ✅ Packaging & Presentation
  ✅ Delivery & Shipping
  ✅ Variety & Curation
  ✅ Customer Service

=================================================================
     TF-IDF EXTRACTIVE SUMMARY (FINAL)
=================================================================

📌 Overall Summary:
Really high quality amazing tea leaf/blends that are such great value and a really good way to try out different teas that you maybe always wanted to try or thought about trying but didn’t want to spend a in if cash on something you may not enjoy! I’ve spent thousands over the years trying beauty products from the regular store and end up wasting my money with products that either make me breakout, aren’t right for my skin tone, don’t match my red hair, terrible quality, have horrible chemicals, or a thousand other reasons!

📌 Product Quality:
Really high quality amazing tea leaf/blends that are such great value and a really good way to try out different teas that you maybe always wanted to try or thought about trying but didn’t want to spend a in if cash on something you may not enjoy!

📌 Value for Money:
Really high quality amazing tea leaf/blends that are such great value and a really good way to try out different teas that you maybe always wanted to try or thought about trying but didn’t want to spend a in if cash on something you may not enjoy!

📌 Packaging & Presentation:
I just wanted to write a review to make sure people know the "all mask" box was an anomaly - usually the Allure beauty boxes contain fantastic samples of makeup and products that I love.

📌 Delivery & Shipping:
Getting a surprise delivery like this is so much fun, and the products I got in my first box are things that I basically use every day (except for the Picky Bar, I ate that right away).

📌 Variety & Curation:
Really high quality amazing tea leaf/blends that are such great value and a really good way to try out different teas that you maybe always wanted to try or thought about trying but didn’t want to spend a in if cash on something you may not enjoy!

📌 Customer Service:
Numerous people complained that their electronic lantern in the fall box was broken and didn't work... Pusheen Box did not offer refunds to anyone... and instead told them to go find EXTREMELY specific battery brands to use in the lantern (which didn't fix the problem).

In [22]:
# Machine translation

In [23]:
# Step 1: Install
!pip install deep-translator

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 4.6 MB/s eta 0:00:00
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4

In [24]:
# Step 2: Translate TF-IDF summary using Google Translate
from deep_translator import GoogleTranslator

def translate_tfidf_summary(summary, target_lang):
    translated = {
        'Overall Summary': {
            'Summary'   : GoogleTranslator(source='en', target=target_lang).translate(summary['Overall Summary']['Summary']),
            'Key Themes': GoogleTranslator(source='en', target=target_lang).translate(summary['Overall Summary']['Key Themes'])
        },
        'Feature-Based Summary': {
            feat: {'Summary': GoogleTranslator(source='en', target=target_lang).translate(details['Summary'])}
            for feat, details in summary['Feature-Based Summary'].items()
        }
    }
    return translated

# Translate
tfidf_tamil_summary     = translate_tfidf_summary(tfidf_summary_clean, 'ta')
tfidf_malayalam_summary = translate_tfidf_summary(tfidf_summary_clean, 'ml')

# Print Tamil
print("="*60)
print("     TF-IDF SUMMARY — TAMIL (Google Translate)")
print("="*60)
print(f"\n📌 Overall Summary:\n{tfidf_tamil_summary['Overall Summary']['Summary']}\n")
for feat, details in tfidf_tamil_summary['Feature-Based Summary'].items():
    print(f"📌 {feat}:\n{details['Summary']}\n")

# Print Malayalam
print("="*60)
print("     TF-IDF SUMMARY — MALAYALAM (Google Translate)")
print("="*60)
print(f"\n📌 Overall Summary:\n{tfidf_malayalam_summary['Overall Summary']['Summary']}\n")
for feat, details in tfidf_malayalam_summary['Feature-Based Summary'].items():
    print(f"📌 {feat}:\n{details['Summary']}\n")

============================================================
     TF-IDF SUMMARY — TAMIL (Google Translate)
============================================================

📌 Overall Summary:
உண்மையிலேயே உயர்தர அற்புதமான தேயிலை இலைகள்/கலவைகள் மிகவும் மதிப்பு வாய்ந்தவை மற்றும் வெவ்வேறு டீகளை முயற்சிப்பதற்கான ஒரு சிறந்த வழி, நீங்கள் எப்போதும் முயற்சி செய்ய விரும்பலாம் அல்லது முயற்சி செய்ய வேண்டும் என்று நினைத்திருக்கலாம், ஆனால் நீங்கள் அனுபவிக்காதவற்றில் பணத்தை செலவழிக்க விரும்பவில்லை! நான் பல ஆண்டுகளாக வழக்கமான கடையில் இருந்து அழகு சாதனப் பொருட்களை முயற்சித்து, என்னை உடைக்கும், என் சரும நிறத்திற்கு சரியில்லாத, என் சிவப்பு முடிக்கு பொருந்தாத, பயங்கரமான தரம், பயங்கரமான இரசாயனங்கள் அல்லது வேறு ஆயிரம் காரணங்களால் என் பணத்தை வீணடித்துவிட்டேன்!

📌 Product Quality:
உண்மையிலேயே உயர்தர அற்புதமான தேயிலை இலைகள்/கலவைகள் மிகவும் மதிப்பு வாய்ந்தவை மற்றும் வெவ்வேறு டீகளை முயற்சிப்பதற்கான ஒரு சிறந்த வழி, நீங்கள் எப்போதும் முயற்சி செய்ய விரும்பலாம் அல்லது முயற்சி செய்ய வேண்டும் என்று நினைத்திருக்கலாம், ஆனால் நீங்கள் அனுபவிக்காதவற்றில் பணத்தை செலவழிக்க விரும்பவில்லை!

📌 Value for Money:
உண்மையிலேயே உயர்தர அற்புதமான தேயிலை இலைகள்/கலவைகள் மிகவும் மதிப்பு வாய்ந்தவை மற்றும் வெவ்வேறு டீகளை முயற்சிப்பதற்கான ஒரு சிறந்த வழி, நீங்கள் எப்போதும் முயற்சி செய்ய விரும்பலாம் அல்லது முயற்சி செய்ய வேண்டும் என்று நினைத்திருக்கலாம், ஆனால் நீங்கள் அனுபவிக்காதவற்றில் பணத்தை செலவழிக்க விரும்பவில்லை!

📌 Packaging & Presentation:
"அனைத்து மாஸ்க்" பெட்டியும் ஒரு ஒழுங்கின்மை என்பதை மக்கள் அறிந்து கொள்வதற்காக நான் ஒரு மதிப்பாய்வை எழுத விரும்பினேன் - பொதுவாக அல்லூர் அழகு பெட்டிகளில் நான் விரும்பும் மேக்கப் மற்றும் தயாரிப்புகளின் அருமையான மாதிரிகள் இருக்கும்.

📌 Delivery & Shipping:
இதுபோன்ற சர்ப்ரைஸ் டெலிவரி பெறுவது மிகவும் வேடிக்கையாக உள்ளது, மேலும் எனது முதல் பெட்டியில் கிடைத்த தயாரிப்புகள் நான் தினமும் பயன்படுத்தும் பொருட்கள் (பிக்கி பார் தவிர, நான் அதை உடனே சாப்பிட்டேன்).

📌 Variety & Curation:
உண்மையிலேயே உயர்தர அற்புதமான தேயிலை இலைகள்/கலவைகள் மிகவும் மதிப்பு வாய்ந்தவை மற்றும் வெவ்வேறு டீகளை முயற்சிப்பதற்கான ஒரு சிறந்த வழி, நீங்கள் எப்போதும் முயற்சி செய்ய விரும்பலாம் அல்லது முயற்சி செய்ய வேண்டும் என்று நினைத்திருக்கலாம், ஆனால் நீங்கள் அனுபவிக்காதவற்றில் பணத்தை செலவழிக்க விரும்பவில்லை!

📌 Customer Service:
ஃபால் பாக்ஸில் இருந்த எலக்ட்ரானிக் லாந்தர் உடைந்து வேலை செய்யவில்லை என்று பலர் புகார் கூறினர்... புஷீன் பாக்ஸ் யாருக்கும் பணத்தைத் திருப்பித் தரவில்லை... அதற்குப் பதிலாக விளக்கில் பயன்படுத்த மிகவும் குறிப்பிட்ட பேட்டரி பிராண்டுகளைக் கண்டறியச் சொன்னார்கள் (அது சிக்கலை சரிசெய்யவில்லை).

============================================================
     TF-IDF SUMMARY — MALAYALAM (Google Translate)
============================================================

📌 Overall Summary:
ശരിക്കും ഉയർന്ന നിലവാരമുള്ള അതിശയകരമായ ടീ ലീഫ്/ബ്ലൻഡുകൾ, അത്രയും വലിയ മൂല്യമുള്ളതും വ്യത്യസ്തമായ ചായകൾ പരീക്ഷിക്കുന്നതിനുള്ള മികച്ച മാർഗവുമാണ്, നിങ്ങൾ എപ്പോഴും ശ്രമിക്കാൻ ആഗ്രഹിച്ചേക്കാം അല്ലെങ്കിൽ ശ്രമിക്കണമെന്ന് ചിന്തിച്ചേക്കാം, എന്നാൽ നിങ്ങൾക്ക് ആസ്വദിക്കാൻ കഴിയാത്ത ഒന്നിൽ പണം ചെലവഴിക്കാൻ ആഗ്രഹിക്കില്ല! ഞാൻ സാധാരണ സ്റ്റോറിൽ നിന്ന് സൗന്ദര്യവർദ്ധക ഉൽപ്പന്നങ്ങൾ പരീക്ഷിച്ചുകൊണ്ട് വർഷങ്ങളായി ആയിരക്കണക്കിന് ചെലവഴിച്ചു, ഒന്നുകിൽ എന്നെ ബ്രേക്ക്ഔട്ട് ആക്കുന്ന, എൻ്റെ ചർമ്മത്തിന് അനുയോജ്യമല്ലാത്ത, എൻ്റെ ചുവന്ന മുടിയുമായി പൊരുത്തപ്പെടാത്ത, ഭയങ്കരമായ ഗുണമേന്മയുള്ള, ഭയാനകമായ രാസവസ്തുക്കളോ മറ്റ് ആയിരം കാരണങ്ങളോ ഉള്ള ഉൽപ്പന്നങ്ങൾ ഉപയോഗിച്ച് എൻ്റെ പണം പാഴാക്കുന്നു!

📌 Product Quality:
ശരിക്കും ഉയർന്ന നിലവാരമുള്ള അതിശയകരമായ ടീ ലീഫ്/ബ്ലൻഡുകൾ, അത്രയും വലിയ മൂല്യമുള്ളതും വ്യത്യസ്തമായ ചായകൾ പരീക്ഷിക്കുന്നതിനുള്ള മികച്ച മാർഗവുമാണ്, നിങ്ങൾ എപ്പോഴും ശ്രമിക്കാൻ ആഗ്രഹിച്ചേക്കാം അല്ലെങ്കിൽ ശ്രമിക്കണമെന്ന് ചിന്തിച്ചേക്കാം, എന്നാൽ നിങ്ങൾക്ക് ആസ്വദിക്കാൻ കഴിയാത്ത ഒന്നിൽ പണം ചെലവഴിക്കാൻ ആഗ്രഹിക്കില്ല!

📌 Value for Money:
ശരിക്കും ഉയർന്ന നിലവാരമുള്ള അതിശയകരമായ ടീ ലീഫ്/ബ്ലൻഡുകൾ, അത്രയും വലിയ മൂല്യമുള്ളതും വ്യത്യസ്തമായ ചായകൾ പരീക്ഷിക്കുന്നതിനുള്ള മികച്ച മാർഗവുമാണ്, നിങ്ങൾ എപ്പോഴും ശ്രമിക്കാൻ ആഗ്രഹിച്ചേക്കാം അല്ലെങ്കിൽ ശ്രമിക്കണമെന്ന് ചിന്തിച്ചേക്കാം, എന്നാൽ നിങ്ങൾക്ക് ആസ്വദിക്കാൻ കഴിയാത്ത ഒന്നിൽ പണം ചെലവഴിക്കാൻ ആഗ്രഹിക്കില്ല!

📌 Packaging & Presentation:
"എല്ലാ മാസ്‌ക്" ബോക്‌സും ഒരു അപാകതയാണെന്ന് ആളുകൾക്ക് അറിയാമെന്ന് ഉറപ്പാക്കാൻ ഞാൻ ഒരു അവലോകനം എഴുതാൻ ആഗ്രഹിച്ചു - സാധാരണയായി Allure ബ്യൂട്ടി ബോക്സുകളിൽ ഞാൻ ഇഷ്ടപ്പെടുന്ന മേക്കപ്പിൻ്റെയും ഉൽപ്പന്നങ്ങളുടെയും അതിശയകരമായ സാമ്പിളുകൾ അടങ്ങിയിരിക്കുന്നു.

📌 Delivery & Shipping:
ഇതുപോലൊരു സർപ്രൈസ് ഡെലിവറി ലഭിക്കുന്നത് വളരെ രസകരമാണ്, എൻ്റെ ആദ്യ ബോക്സിൽ ലഭിച്ച ഉൽപ്പന്നങ്ങൾ ഞാൻ അടിസ്ഥാനപരമായി എല്ലാ ദിവസവും ഉപയോഗിക്കുന്നവയാണ് (പിക്കി ബാർ ഒഴികെ, ഞാൻ അത് ഉടനെ കഴിച്ചു).

📌 Variety & Curation:
ശരിക്കും ഉയർന്ന നിലവാരമുള്ള അതിശയകരമായ ടീ ലീഫ്/ബ്ലൻഡുകൾ, അത്രയും വലിയ മൂല്യമുള്ളതും വ്യത്യസ്തമായ ചായകൾ പരീക്ഷിക്കുന്നതിനുള്ള മികച്ച മാർഗവുമാണ്, നിങ്ങൾ എപ്പോഴും ശ്രമിക്കാൻ ആഗ്രഹിച്ചേക്കാം അല്ലെങ്കിൽ ശ്രമിക്കണമെന്ന് ചിന്തിച്ചേക്കാം, എന്നാൽ നിങ്ങൾക്ക് ആസ്വദിക്കാൻ കഴിയാത്ത ഒന്നിൽ പണം ചെലവഴിക്കാൻ ആഗ്രഹിക്കില്ല!

📌 Customer Service:
വീഴ്ച്ച പെട്ടിയിലെ തങ്ങളുടെ ഇലക്ട്രോണിക് ലാൻ്റേൺ പൊട്ടിയെന്നും അത് പ്രവർത്തിക്കുന്നില്ലെന്നും നിരവധി ആളുകൾ പരാതിപ്പെട്ടു... പുഷീൻ ബോക്സ് ആർക്കും റീഫണ്ട് വാഗ്ദാനം ചെയ്തില്ല... പകരം ലാൻ്റേണിൽ ഉപയോഗിക്കാനുള്ള പ്രത്യേക ബാറ്ററി ബ്രാൻഡുകൾ കണ്ടെത്താൻ അവരോട് പറഞ്ഞു (ഇത് പ്രശ്നം പരിഹരിച്ചില്ല).

In [25]:
# evlauation

In [26]:
!pip install sacrebleu rouge-score langdetect deep-translator

Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 25.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: deep-translator in /usr/local/lib/python3.12/dist-packages (1.11.4)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.0.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (4.67.3)
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 5.6 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Building wheels for collected packages: rouge-score, langdetect
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=2fe648fe40a8e4751569849524cb1a21c8e4dc1b49c58115043a07291b123a93
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=397072ae7e0f40153c642510437ecc677fa189494442488c562e02e7699525c9
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built rouge-score langdetect
Installing collected packages: portalocker, langdetect, colorama, sacrebleu, rouge-score
Successfully installed colorama-0.4.6 langdetect-1.0.9 portalocker-3.2.0 rouge-score-0.1.2 sacrebleu-2.6.0

In [27]:
# CELL: Evaluate TF-IDF Google Translate — Tamil and Malayalam
from sacrebleu.metrics import CHRF
from rouge_score import rouge_scorer
from langdetect import detect
from deep_translator import GoogleTranslator
import pandas as pd

chrf   = CHRF()
scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)

def back_translate(text, src):
    try:
        return GoogleTranslator(source=src, target='en').translate(text)
    except:
        return ""

def evaluate_tfidf(tfidf_clean, tfidf_translated, src_lang, lang_name):
    results = []

    # Overall Summary
    orig  = tfidf_clean['Overall Summary']['Summary']
    trans = tfidf_translated['Overall Summary']['Summary']
    back  = back_translate(trans, src_lang)
    orig_words = set(orig.lower().split())
    back_words = set(back.lower().split())
    results.append({
        'Feature'        : 'Overall Summary',
        'chrF Score'     : round(chrf.sentence_score(back, [orig]).score, 2),
        'ROUGE-L'        : round(scorer.score(orig, back)['rougeL'].fmeasure, 3),
        'Word Overlap %' : round(len(orig_words & back_words) / len(orig_words) * 100, 1),
        'Lang Detected'  : detect(back)
    })

    # Feature summaries
    orig_feats  = tfidf_clean['Feature-Based Summary']
    trans_feats = tfidf_translated['Feature-Based Summary']
    for feat in orig_feats:
        orig  = orig_feats[feat]['Summary']
        trans = trans_feats[feat]['Summary']
        back  = back_translate(trans, src_lang)
        if not back.strip():
            continue
        orig_words = set(orig.lower().split())
        back_words = set(back.lower().split())
        results.append({
            'Feature'        : feat,
            'chrF Score'     : round(chrf.sentence_score(back, [orig]).score, 2),
            'ROUGE-L'        : round(scorer.score(orig, back)['rougeL'].fmeasure, 3),
            'Word Overlap %' : round(len(orig_words & back_words) / len(orig_words) * 100, 1),
            'Lang Detected'  : detect(back)
        })

    df = pd.DataFrame(results)
    print(f"\n{'='*65}")
    print(f"  TF-IDF — {lang_name.upper()} EVALUATION (Google Translate)")
    print(f"{'='*65}")
    print(df[['Feature','chrF Score','ROUGE-L','Word Overlap %','Lang Detected']].to_string(index=False))
    print(f"\n  Avg chrF    : {df['chrF Score'].mean():.2f} / 100")
    print(f"  Avg ROUGE-L : {df['ROUGE-L'].mean():.3f} / 1.0")
    print(f"  Avg Overlap : {df['Word Overlap %'].mean():.1f}%")
    print(f"  Lang Check  : {(df['Lang Detected'] == 'en').sum()}/{len(df)} ✅")
    return df

df_tfidf_tamil     = evaluate_tfidf(tfidf_summary_clean, tfidf_tamil_summary,     'ta', 'Tamil')
df_tfidf_malayalam = evaluate_tfidf(tfidf_summary_clean, tfidf_malayalam_summary, 'ml', 'Malayalam')

# Side by side
print(f"\n{'='*65}")
print("  TF-IDF — TAMIL vs MALAYALAM COMPARISON")
print(f"{'='*65}")
print(f"  {'Metric':<22} {'Tamil':>10} {'Malayalam':>12}")
print(f"  {'─'*45}")
print(f"  {'Avg chrF':<22} {df_tfidf_tamil['chrF Score'].mean():>10.2f} {df_tfidf_malayalam['chrF Score'].mean():>12.2f}")
print(f"  {'Avg ROUGE-L':<22} {df_tfidf_tamil['ROUGE-L'].mean():>10.3f} {df_tfidf_malayalam['ROUGE-L'].mean():>12.3f}")
print(f"  {'Avg Overlap %':<22} {df_tfidf_tamil['Word Overlap %'].mean():>10.1f} {df_tfidf_malayalam['Word Overlap %'].mean():>12.1f}")
print(f"{'='*65}")

=================================================================
  TF-IDF — TAMIL EVALUATION (Google Translate)
=================================================================
                 Feature  chrF Score  ROUGE-L  Word Overlap % Lang Detected
         Overall Summary       63.98    0.714            64.1            en
         Product Quality       62.24    0.703            65.0            en
         Value for Money       62.24    0.703            65.0            en
Packaging & Presentation       78.32    0.848            84.4            en
     Delivery & Shipping       69.90    0.795            75.8            en
      Variety & Curation       62.24    0.703            65.0            en
        Customer Service       68.64    0.710            61.1            en

  Avg chrF    : 66.79 / 100
  Avg ROUGE-L : 0.739 / 1.0
  Avg Overlap : 68.6%
  Lang Check  : 7/7 ✅

=================================================================
  TF-IDF — MALAYALAM EVALUATION (Google Translate)
=================================================================
                 Feature  chrF Score  ROUGE-L  Word Overlap % Lang Detected
         Overall Summary       72.60    0.770            67.9            en
         Product Quality       68.66    0.703            70.0            en
         Value for Money       68.66    0.703            70.0            en
Packaging & Presentation       79.61    0.866            87.5            en
     Delivery & Shipping       72.17    0.773            78.8            en
      Variety & Curation       68.66    0.703            70.0            en
        Customer Service       79.39    0.813            77.8            en

  Avg chrF    : 72.82 / 100
  Avg ROUGE-L : 0.762 / 1.0
  Avg Overlap : 74.6%
  Lang Check  : 7/7 ✅

=================================================================
  TF-IDF — TAMIL vs MALAYALAM COMPARISON
=================================================================
  Metric                      Tamil    Malayalam
  ─────────────────────────────────────────────
  Avg chrF                    66.79        72.82
  Avg ROUGE-L                 0.739        0.762
  Avg Overlap %                68.6         74.6
=================================================================

In [14]:
# IndicTrans2

In [30]:
# Force install correct transformers version
!pip install transformers==4.53.2 --force-reinstall -q
print("✅ Done! Now restart runtime!")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 4.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 98.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 48.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 88.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 53.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 802.0/802.0 kB 58.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 44.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 121.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.7/153.7 kB 15.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 20.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.5/202.5 kB 23.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 130.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 15.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2026.2.0 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.4.3 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.3 which is incompatible.
✅ Done! Now restart runtime!

In [1]:
import transformers
print(f"Version: {transformers.__version__}")
# Must show 4.53.2

Version: 4.53.2

In [2]:
# COMPLETE SETUP — after restart
import torch, sys, glob, os
sys.path.insert(0, '/content/IndicTrans2/huggingface_interface/IndicTransToolkit')
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from IndicTransToolkit.processor import IndicProcessor

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 4
print(f"Device: {DEVICE}")
print(f"Transformers: {__import__('transformers').__version__}")

def clean_translation(text):
    text = text.replace('</s>', '').replace('<pad>', '').replace('<s>', '')
    return ' '.join(text.split()).strip()

def batch_translate(input_sentences, src_lang, tgt_lang, model, tokenizer, ip):
    translations = []
    for i in range(0, len(input_sentences), BATCH_SIZE):
        batch = input_sentences[i:i+BATCH_SIZE]
        batch = ip.preprocess_batch(batch, src_lang=src_lang, tgt_lang=tgt_lang)
        inputs = tokenizer(batch, truncation=True, padding="longest",
                          return_tensors="pt", return_attention_mask=True).to(DEVICE)
        with torch.no_grad():
            generated_tokens = model.generate(
                **inputs, use_cache=True, min_length=0,
                max_length=256, num_beams=5, num_return_sequences=1)
        generated_tokens = tokenizer.batch_decode(
            generated_tokens, skip_special_tokens=True,
            clean_up_tokenization_spaces=True)
        translations += ip.postprocess_batch(generated_tokens, lang=tgt_lang)
        del inputs
        torch.cuda.empty_cache()
    return [clean_translation(t) for t in translations]

# Patch config
hash_path = '/root/.cache/huggingface/modules/transformers_modules/ai4bharat/indictrans2_hyphen_en_hyphen_indic_hyphen_1B/10e65a9951a1e922cd109a95e8aba9357b62144b'
config_path = os.path.join(hash_path, 'configuration_indictrans.py')
with open(config_path, 'r') as f: lines = f.readlines()
cleaned, skip = [], False
for line in lines:
    if 'transformers.onnx' in line: continue
    if 'class IndicTransOnnxConfig' in line: skip = True
    if skip and line.startswith('class ') and 'IndicTransOnnxConfig' not in line: skip = False
    if not skip: cleaned.append(line)
with open(config_path, 'w') as f: f.writelines(cleaned)
print("✅ Patch 1 — config")

tokenizer_path = os.path.join(hash_path, 'tokenization_indictrans.py')
with open(tokenizer_path, 'r') as f: content = f.read()
if '_special_tokens_map_data' not in content:
    patch = '''
    @property
    def _special_tokens_map(self):
        return getattr(self, '_special_tokens_map_data', {})

    @_special_tokens_map.setter
    def _special_tokens_map(self, value):
        self._special_tokens_map_data = value

    @property
    def additional_special_tokens(self):
        return getattr(self, '_additional_special_tokens', [])

    @additional_special_tokens.setter
    def additional_special_tokens(self, value):
        self._additional_special_tokens = value if value is not None else []

'''
    content = content.replace('def get_vocab(self)', f'{patch}\n    def get_vocab(self)')
    with open(tokenizer_path, 'w') as f: f.write(content)
print("✅ Patch 2 — tokenizer")

# Load tokenizer
print("Loading tokenizer...")
en_indic_tokenizer = AutoTokenizer.from_pretrained(
    "ai4bharat/indictrans2-en-indic-1B", trust_remote_code=True)
print("✅ Tokenizer loaded!")

# Patch modeling (now exists after tokenizer load)
all_modeling = glob.glob('/root/.cache/**/*modeling_indictrans*', recursive=True)
for path in all_modeling:
    with open(path, 'r') as f: content = f.read()
    content = content.replace('def tie_weights(self):', 'def tie_weights(self, **kwargs):')
    with open(path, 'w') as f: f.write(content)
    print(f"✅ Patch 3 — modeling")

# Load model
print("Loading model...")
en_indic_model = AutoModelForSeq2SeqLM.from_pretrained(
    "ai4bharat/indictrans2-en-indic-1B", trust_remote_code=True, low_cpu_mem_usage=True)
en_indic_model = en_indic_model.to(DEVICE)
en_indic_model.half()
en_indic_model.eval()
ip = IndicProcessor(inference=True)
print("✅ Model loaded!")

# Test both languages
result_tam = batch_translate(
    ["Customers are often disappointed with the value for money."],
    "eng_Latn", "tam_Taml", en_indic_model, en_indic_tokenizer, ip)
print(f"\nTamil test : {result_tam}")

result_mal = batch_translate(
    ["Customers are often disappointed with the value for money."],
    "eng_Latn", "mal_Mlym", en_indic_model, en_indic_tokenizer, ip)
print(f"Malayalam test: {result_mal}")

Device: cuda
Transformers: 4.53.2
✅ Patch 1 — config
✅ Patch 2 — tokenizer
Loading tokenizer...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

✅ Tokenizer loaded!
✅ Patch 3 — modeling
✅ Patch 3 — modeling
Loading model...
✅ Model loaded!

Tamil test : ['பணத்திற்கான மதிப்பு குறித்து வாடிக்கையாளர்கள் அடிக்கடி ஏமாற்றமடைகிறார்கள்.']
Malayalam test: ['പണത്തിന്റെ മൂല്യത്തിൽ ഉപഭോക്താക്കൾ പലപ്പോഴും നിരാശരാണ്.']

In [5]:
# Define tfidf_summary_clean directly
tfidf_summary_clean = {
    "Overall Summary": {
        "Summary": "Really high quality amazing tea leaf/blends that are such great value and a really good way to try out different teas that you maybe always wanted to try or thought about trying but didn't want to spend a in if cash on something you may not enjoy! I've spent thousands over the years trying beauty products from the regular store and end up wasting my money with products that either make me breakout, aren't right for my skin tone, don't match my red hair, terrible quality, have horrible chemicals, or a thousand other reasons!",
        "Key Themes": "Quality, Value for Money, Customer Service, Variety"
    },
    "Feature-Based Summary": {
        "Product Quality":          {"Summary": "Really high quality amazing tea leaf/blends that are such great value and a really good way to try out different teas that you maybe always wanted to try or thought about trying but didn't want to spend a in if cash on something you may not enjoy!"},
        "Value for Money":          {"Summary": "Really high quality amazing tea leaf/blends that are such great value and a really good way to try out different teas that you maybe always wanted to try or thought about trying but didn't want to spend a in if cash on something you may not enjoy!"},
        "Packaging & Presentation": {"Summary": "I just wanted to write a review to make sure people know the all mask box was an anomaly - usually the Allure beauty boxes contain fantastic samples of makeup and products that I love."},
        "Delivery & Shipping":      {"Summary": "Getting a surprise delivery like this is so much fun, and the products I got in my first box are things that I basically use every day except for the Picky Bar, I ate that right away."},
        "Variety & Curation":       {"Summary": "Really high quality amazing tea leaf/blends that are such great value and a really good way to try out different teas that you maybe always wanted to try or thought about trying but didn't want to spend a in if cash on something you may not enjoy!"},
        "Customer Service":         {"Summary": "The company refunded my money, but they are just a small operation good people and should not have to deal with the lack of communication to cancel additional subscriptions from Amazon."}
    }
}

tfidf_texts = [tfidf_summary_clean['Overall Summary']['Summary']] + \
              [v['Summary'] for v in tfidf_summary_clean['Feature-Based Summary'].values()]

tfidf_feat_names = ['Overall Summary'] + list(tfidf_summary_clean['Feature-Based Summary'].keys())

print("Translating TF-IDF to Tamil...")
tfidf_it2_tamil = batch_translate(tfidf_texts, "eng_Latn", "tam_Taml",
                                   en_indic_model, en_indic_tokenizer, ip)
print("✅ Tamil done!")

print("Translating TF-IDF to Malayalam...")
tfidf_it2_malayalam = batch_translate(tfidf_texts, "eng_Latn", "mal_Mlym",
                                       en_indic_model, en_indic_tokenizer, ip)
print("✅ Malayalam done!")

print("\n" + "="*60 + "\n  TF-IDF — INDICTRANS2 TAMIL\n" + "="*60)
for feat, trans in zip(tfidf_feat_names, tfidf_it2_tamil):
    print(f"\n📌 {feat}\n   {trans}")

print("\n" + "="*60 + "\n  TF-IDF — INDICTRANS2 MALAYALAM\n" + "="*60)
for feat, trans in zip(tfidf_feat_names, tfidf_it2_malayalam):
    print(f"\n📌 {feat}\n   {trans}")

Translating TF-IDF to Tamil...
✅ Tamil done!
Translating TF-IDF to Malayalam...
✅ Malayalam done!

============================================================
  TF-IDF — INDICTRANS2 TAMIL
============================================================

📌 Overall Summary
   உண்மையில் உயர்தரமான அற்புதமான தேநீர் இலை/கலவைகள் மிகவும் மதிப்புமிக்கவை மற்றும் வெவ்வேறு தேநீர்களை முயற்சிக்க ஒரு நல்ல வழி, நீங்கள் எப்போதும் முயற்சி செய்ய விரும்பினீர்கள் அல்லது முயற்சி செய்வதைப் பற்றி யோசித்திருக்கலாம், ஆனால் நீங்கள் விரும்பாத ஒன்றுக்கு பணம் செலவழிக்க விரும்பவில்லை! வழக்கமான கடையில் இருந்து அழகு சாதனப் பொருட்களை முயற்சிக்க நான் ஆயிரக்கணக்கான ஆண்டுகளை செலவிட்டேன், இறுதியில் என் பணத்தை வீணாக்குகிறேன், அவை என்னை உடைக்கச் செய்கின்றன, என் தோல் நிறத்திற்கு ஏற்றவை அல்ல, என் சிவப்பு முடி, பயங்கரமான தரம், பயங்கரமான இரசாயனங்கள் அல்லது ஆயிரம் பிற காரணங்களுடன் பொருந்தாது!

📌 Product Quality
   உண்மையில் உயர்தர அற்புதமான தேநீர் இலை/கலவைகள் மிகவும் மதிப்புமிக்கவை மற்றும் வெவ்வேறு தேநீர்களை முயற்சிக்க ஒரு நல்ல வழி, நீங்கள் எப்போதும் முயற்சி செய்ய விரும்பினீர்கள் அல்லது முயற்சி செய்ய நினைத்தீர்கள், ஆனால் நீங்கள் விரும்பாத ஒன்றுக்கு பணம் செலவழிக்க விரும்பவில்லை!

📌 Value for Money
   உண்மையில் உயர்தர அற்புதமான தேநீர் இலை/கலவைகள் மிகவும் மதிப்புமிக்கவை மற்றும் வெவ்வேறு தேநீர்களை முயற்சிக்க ஒரு நல்ல வழி, நீங்கள் எப்போதும் முயற்சி செய்ய விரும்பினீர்கள் அல்லது முயற்சி செய்ய நினைத்தீர்கள், ஆனால் நீங்கள் விரும்பாத ஒன்றுக்கு பணம் செலவழிக்க விரும்பவில்லை!

📌 Packaging & Presentation
   அனைத்து முகமூடி பெட்டியும் ஒரு ஒழுங்கின்மை என்பதை மக்கள் அறிந்திருப்பதை உறுதிசெய்ய நான் ஒரு மதிப்பாய்வை எழுத விரும்பினேன்-வழக்கமாக அல்யூர் அழகு பெட்டிகளில் ஒப்பனை மற்றும் நான் விரும்பும் தயாரிப்புகளின் அற்புதமான மாதிரிகள் உள்ளன.

📌 Delivery & Shipping
   இது போன்ற ஒரு ஆச்சரியமான டெலிவரி பெறுவது மிகவும் வேடிக்கையாக இருக்கிறது, மேலும் எனது முதல் பெட்டியில் எனக்கு கிடைத்த தயாரிப்புகள் அடிப்படையில் பிக்கி பார் தவிர ஒவ்வொரு நாளும் நான் பயன்படுத்தும் விஷயங்கள், நான் அதை உடனே சாப்பிட்டேன்.

📌 Variety & Curation
   உண்மையில் உயர்தர அற்புதமான தேநீர் இலை/கலவைகள் மிகவும் மதிப்புமிக்கவை மற்றும் வெவ்வேறு தேநீர்களை முயற்சிக்க ஒரு நல்ல வழி, நீங்கள் எப்போதும் முயற்சி செய்ய விரும்பினீர்கள் அல்லது முயற்சி செய்ய நினைத்தீர்கள், ஆனால் நீங்கள் விரும்பாத ஒன்றுக்கு பணம் செலவழிக்க விரும்பவில்லை!

📌 Customer Service
   நிறுவனம் எனது பணத்தை திருப்பிச் செலுத்தியது, ஆனால் அவர்கள் ஒரு சிறிய செயல்பாட்டு நல்ல மனிதர்கள் மற்றும் அமேசானிலிருந்து கூடுதல் சந்தாக்களை ரத்து செய்ய தகவல்தொடர்பு இல்லாததை சமாளிக்க வேண்டியதில்லை.

============================================================
  TF-IDF — INDICTRANS2 MALAYALAM
============================================================

📌 Overall Summary
   ശരിക്കും ഉയർന്ന നിലവാരമുള്ള അത്ഭുതകരമായ തേയില ഇല/മിശ്രിതങ്ങൾ, നിങ്ങൾ എല്ലായ്പ്പോഴും ശ്രമിക്കാനോ ശ്രമിക്കാനോ ആഗ്രഹിക്കുന്ന വ്യത്യസ്ത തേയിലകൾ പരീക്ഷിക്കാനുള്ള ഒരു നല്ല മാർഗ്ഗം, പക്ഷേ നിങ്ങൾ ആസ്വദിക്കാത്ത എന്തെങ്കിലും പണം ചെലവഴിക്കാൻ ആഗ്രഹിക്കുന്നില്ല! പതിവ് സ്റ്റോറിൽ നിന്നുള്ള സൌന്ദര്യവർദ്ധക ഉൽപ്പന്നങ്ങൾ പരീക്ഷിക്കാൻ ഞാൻ ആയിരക്കണക്കിന് വർഷങ്ങൾ ചെലവഴിച്ചു, ഒടുവിൽ എന്നെ ബ്രേക്ക്ഔട്ട് ആക്കുന്ന, ചർമ്മത്തിന് അനുയോജ്യമല്ലാത്ത, എന്റെ ചുവന്ന മുടിയുമായി പൊരുത്തപ്പെടാത്ത, ഭയാനകമായ ഗുണനിലവാരം, ഭയാനകമായ രാസവസ്തുക്കൾ, അല്ലെങ്കിൽ മറ്റ് ആയിരം കാരണങ്ങൾ എന്നിവ ഉപയോഗിച്ച് എന്റെ പണം പാഴാക്കുന്നു!

📌 Product Quality
   ശരിക്കും ഉയർന്ന നിലവാരമുള്ള അത്ഭുതകരമായ തേയില ഇല/മിശ്രിതങ്ങൾ വളരെ മികച്ച മൂല്യമുള്ളതും വ്യത്യസ്ത തേയിലകൾ പരീക്ഷിക്കാനുള്ള ഒരു നല്ല മാർഗവുമാണ്, നിങ്ങൾ എല്ലായ്പ്പോഴും ശ്രമിക്കാൻ ആഗ്രഹിക്കുകയോ ശ്രമിക്കാൻ ചിന്തിക്കുകയോ ചെയ്തേക്കാം, പക്ഷേ നിങ്ങൾ ആസ്വദിക്കാത്ത എന്തെങ്കിലും പണം ചെലവഴിക്കാൻ ആഗ്രഹിക്കുന്നില്ല!

📌 Value for Money
   ശരിക്കും ഉയർന്ന നിലവാരമുള്ള അത്ഭുതകരമായ തേയില ഇല/മിശ്രിതങ്ങൾ വളരെ മികച്ച മൂല്യമുള്ളതും വ്യത്യസ്ത തേയിലകൾ പരീക്ഷിക്കാനുള്ള ഒരു നല്ല മാർഗവുമാണ്, നിങ്ങൾ എല്ലായ്പ്പോഴും ശ്രമിക്കാൻ ആഗ്രഹിക്കുകയോ ശ്രമിക്കാൻ ചിന്തിക്കുകയോ ചെയ്തേക്കാം, പക്ഷേ നിങ്ങൾ ആസ്വദിക്കാത്ത എന്തെങ്കിലും പണം ചെലവഴിക്കാൻ ആഗ്രഹിക്കുന്നില്ല!

📌 Packaging & Presentation
   മാസ്ക് ബോക്സ് ഒരു അസ്വാഭാവികതയാണെന്ന് ആളുകൾക്ക് അറിയാമെന്ന് ഉറപ്പാക്കാൻ ഞാൻ ഒരു അവലോകനം എഴുതാൻ ആഗ്രഹിച്ചു-സാധാരണയായി അല്യൂർ ബ്യൂട്ടി ബോക്സുകളിൽ മേക്കപ്പിന്റെയും ഞാൻ ഇഷ്ടപ്പെടുന്ന ഉൽപ്പന്നങ്ങളുടെയും അതിശയകരമായ സാമ്പിളുകൾ അടങ്ങിയിരിക്കുന്നു.

📌 Delivery & Shipping
   ഇതുപോലുള്ള ഒരു സർപ്രൈസ് ഡെലിവറി ലഭിക്കുന്നത് വളരെ രസകരമാണ്, എന്റെ ആദ്യ ബോക്സിൽ എനിക്ക് ലഭിച്ച ഉൽപ്പന്നങ്ങൾ അടിസ്ഥാനപരമായി ഞാൻ എല്ലാ ദിവസവും ഉപയോഗിക്കുന്ന കാര്യങ്ങളാണ്, പിക്കി ബാർ ഒഴികെ, ഞാൻ അത് ഉടൻ തന്നെ കഴിച്ചു.

📌 Variety & Curation
   ശരിക്കും ഉയർന്ന നിലവാരമുള്ള അത്ഭുതകരമായ തേയില ഇല/മിശ്രിതങ്ങൾ വളരെ മികച്ച മൂല്യമുള്ളതും വ്യത്യസ്ത തേയിലകൾ പരീക്ഷിക്കാനുള്ള ഒരു നല്ല മാർഗവുമാണ്, നിങ്ങൾ എല്ലായ്പ്പോഴും ശ്രമിക്കാൻ ആഗ്രഹിക്കുകയോ ശ്രമിക്കാൻ ചിന്തിക്കുകയോ ചെയ്തേക്കാം, പക്ഷേ നിങ്ങൾ ആസ്വദിക്കാത്ത എന്തെങ്കിലും പണം ചെലവഴിക്കാൻ ആഗ്രഹിക്കുന്നില്ല!

📌 Customer Service
   കമ്പനി എന്റെ പണം തിരികെ നൽകി, പക്ഷേ അവർ ഒരു ചെറിയ ഓപ്പറേഷൻ നല്ല ആളുകളാണ്, ആമസോണിൽ നിന്നുള്ള അധിക സബ്സ്ക്രിപ്ഷനുകൾ റദ്ദാക്കുന്നതിന് ആശയവിനിമയത്തിന്റെ അഭാവം കൈകാര്യം ചെയ്യേണ്ടതില്ല.

In [6]:
# Evaluate TF-IDF IndicTrans2
from sacrebleu.metrics import CHRF
from rouge_score import rouge_scorer
from langdetect import detect
from deep_translator import GoogleTranslator
import pandas as pd

chrf   = CHRF()
scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)

def back_translate(text, src):
    try:
        return GoogleTranslator(source=src, target='en').translate(text)
    except:
        return ""

def evaluate(orig_texts, translations, src_lang, lang_name, feat_names):
    results = []
    for orig, trans, feat in zip(orig_texts, translations, feat_names):
        back = back_translate(trans, src_lang)
        if not back.strip(): continue
        orig_words = set(orig.lower().split())
        back_words = set(back.lower().split())
        results.append({
            'Feature'        : feat,
            'chrF Score'     : round(chrf.sentence_score(back, [orig]).score, 2),
            'ROUGE-L'        : round(scorer.score(orig, back)['rougeL'].fmeasure, 3),
            'Word Overlap %' : round(len(orig_words & back_words) / len(orig_words) * 100, 1),
            'Lang Detected'  : detect(back)
        })
    df = pd.DataFrame(results)
    print(f"\n{'='*65}\n  {lang_name.upper()} — EVALUATION\n{'='*65}")
    print(df[['Feature','chrF Score','ROUGE-L','Word Overlap %','Lang Detected']].to_string(index=False))
    print(f"\n  Avg chrF    : {df['chrF Score'].mean():.2f} / 100")
    print(f"  Avg ROUGE-L : {df['ROUGE-L'].mean():.3f} / 1.0")
    print(f"  Avg Overlap : {df['Word Overlap %'].mean():.1f}%")
    print(f"  Lang Check  : {(df['Lang Detected'] == 'en').sum()}/{len(df)} ✅")
    return df

df_tfidf_it2_tamil     = evaluate(tfidf_texts, tfidf_it2_tamil,
                                   'ta', 'TF-IDF IndicTrans2 Tamil',     tfidf_feat_names)
df_tfidf_it2_malayalam = evaluate(tfidf_texts, tfidf_it2_malayalam,
                                   'ml', 'TF-IDF IndicTrans2 Malayalam', tfidf_feat_names)

# GT baseline scores from earlier session
gt_tamil_avg     = {'chrF': 66.67, 'ROUGE-L': 0.730, 'Overlap': 70.0}
gt_malayalam_avg = {'chrF': 74.25, 'ROUGE-L': 0.774, 'Overlap': 76.2}

print(f"\n{'='*70}")
print("  TF-IDF: Google Translate vs IndicTrans2")
print(f"{'='*70}")
print(f"  {'Metric':<22} {'GT Tamil':>9} {'IT2 Tamil':>10} {'GT Malay':>10} {'IT2 Malay':>10}")
print(f"  {'─'*62}")
print(f"  {'Avg chrF':<22} {gt_tamil_avg['chrF']:>9.2f} {df_tfidf_it2_tamil['chrF Score'].mean():>10.2f} {gt_malayalam_avg['chrF']:>10.2f} {df_tfidf_it2_malayalam['chrF Score'].mean():>10.2f}")
print(f"  {'Avg ROUGE-L':<22} {gt_tamil_avg['ROUGE-L']:>9.3f} {df_tfidf_it2_tamil['ROUGE-L'].mean():>10.3f} {gt_malayalam_avg['ROUGE-L']:>9.3f} {df_tfidf_it2_malayalam['ROUGE-L'].mean():>10.3f}")
print(f"  {'Avg Overlap %':<22} {gt_tamil_avg['Overlap']:>9.1f} {df_tfidf_it2_tamil['Word Overlap %'].mean():>10.1f} {gt_malayalam_avg['Overlap']:>9.1f} {df_tfidf_it2_malayalam['Word Overlap %'].mean():>10.1f}")
print(f"{'='*70}")
print(f"\n  Winner Tamil   chrF   : {'IndicTrans2 ✅' if df_tfidf_it2_tamil['chrF Score'].mean() > gt_tamil_avg['chrF'] else 'Google Translate ✅'}")
print(f"  Winner Tamil   ROUGE-L: {'IndicTrans2 ✅' if df_tfidf_it2_tamil['ROUGE-L'].mean() > gt_tamil_avg['ROUGE-L'] else 'Google Translate ✅'}")
print(f"  Winner Malay   chrF   : {'IndicTrans2 ✅' if df_tfidf_it2_malayalam['chrF Score'].mean() > gt_malayalam_avg['chrF'] else 'Google Translate ✅'}")
print(f"  Winner Malay   ROUGE-L: {'IndicTrans2 ✅' if df_tfidf_it2_malayalam['ROUGE-L'].mean() > gt_malayalam_avg['ROUGE-L'] else 'Google Translate ✅'}")
print(f"{'='*70}")

=================================================================
  TF-IDF INDICTRANS2 TAMIL — EVALUATION
=================================================================
                 Feature  chrF Score  ROUGE-L  Word Overlap % Lang Detected
         Overall Summary       72.30    0.754            71.8            en
         Product Quality       70.56    0.769            72.5            en
         Value for Money       70.56    0.769            72.5            en
Packaging & Presentation       72.87    0.866            78.1            en
     Delivery & Shipping       67.31    0.757            75.8            en
      Variety & Curation       70.56    0.769            72.5            en
        Customer Service       76.16    0.774            79.3            en

  Avg chrF    : 71.47 / 100
  Avg ROUGE-L : 0.780 / 1.0
  Avg Overlap : 74.6%
  Lang Check  : 7/7 ✅

=================================================================
  TF-IDF INDICTRANS2 MALAYALAM — EVALUATION
=================================================================
                 Feature  chrF Score  ROUGE-L  Word Overlap % Lang Detected
         Overall Summary       69.97    0.754            69.2            en
         Product Quality       68.02    0.756            70.0            en
         Value for Money       68.02    0.756            70.0            en
Packaging & Presentation       71.30    0.818            75.0            en
     Delivery & Shipping       69.38    0.795            75.8            en
      Variety & Curation       68.02    0.756            70.0            en
        Customer Service       82.43    0.900            86.2            en

  Avg chrF    : 71.02 / 100
  Avg ROUGE-L : 0.791 / 1.0
  Avg Overlap : 73.7%
  Lang Check  : 7/7 ✅

======================================================================
  TF-IDF: Google Translate vs IndicTrans2
======================================================================
  Metric                  GT Tamil  IT2 Tamil   GT Malay  IT2 Malay
  ──────────────────────────────────────────────────────────────
  Avg chrF                   66.67      71.47      74.25      71.02
  Avg ROUGE-L                0.730      0.780     0.774      0.791
  Avg Overlap %               70.0       74.6      76.2       73.7
======================================================================

  Winner Tamil   chrF   : IndicTrans2 ✅
  Winner Tamil   ROUGE-L: IndicTrans2 ✅
  Winner Malay   chrF   : Google Translate ✅
  Winner Malay   ROUGE-L: IndicTrans2 ✅
======================================================================